
CREATE MEMORY TABLE "PUBLIC"."USER"(
    "SOURCEDID" VARCHAR(255) NOT NULL,
    "DATELASTMODIFIED" TIMESTAMP,
    "METADATA" VARCHAR(255),
    "STATUS" BOOLEAN,
    "AGENTS" VARCHAR(255),
    "EMAIL" VARCHAR(255),
    "ENABLEDUSER" BOOLEAN,
    "FAMILYNAME" VARCHAR(255),
    "GIVENNAME" VARCHAR(255),
    "GRADES" VARCHAR(255),
    "IDENTIFIER" VARCHAR(255),
    "MIDDLENAME" VARCHAR(255),
    "ORGS" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    "PHONE" VARCHAR(255),
    "ROLE" VARCHAR(255),
    "SMS" VARCHAR(255),
    "USERIDS" VARCHAR(255),
    "USERNAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("SOURCEDID");
