
CREATE MEMORY TABLE "PUBLIC"."USER"(
    "SOURCED_ID" VARCHAR(255) NOT NULL,
    "DATE_LAST_MODIFIED" TIMESTAMP,
    "METADATA" VARCHAR(255),
    "STATUS" BOOLEAN,
    "AGENTS" VARCHAR(255),
    "EMAIL" VARCHAR(255),
    "ENABLED_USER" BOOLEAN,
    "FAMILY_NAME" VARCHAR(255),
    "GIVEN_NAME" VARCHAR(255),
    "GRADES" VARCHAR(255),
    "IDENTIFIER" VARCHAR(255),
    "MIDDLE_NAME" VARCHAR(255),
    "ORGS" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    "PHONE" VARCHAR(255),
    "ROLE" VARCHAR(255),
    "SMS" VARCHAR(255),
    "USER_IDS" VARCHAR(255),
    "USERNAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("SOURCED_ID");
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USER;
-- INSERT INTO "PUBLIC"."USER" VALUES
-- ('4ff34829-c73b-4b97-a389-6e5e08a56434', TIMESTAMP '2019-05-30 22:40:01.128', NULL, TRUE, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
